### ISSUE TITLE
Blank screen is visible.

### ISSUE THREAD

**Issue by Praveenmishra123** [praween05/Android-SignalView#1]
I have downloaded the sample code and then run it, a blank screen is displaying. Signal view not showing.

**Comment by praween05** [comment]
can you please let me know the os version and all.

**Comment by Krunal-Kevadiya** [comment]
Hi Friends,
  i have resolve issue and re-format with proper design and adjust signal strength indicator base on dynamic layout size change.  Please [check here](https://gist.github.com/Krunal-Kevadiya/518f5949a016a0afd463a93d39bcb1e6) to my answer.

**Comment by praween05** [comment]
closing the issue as it is solved
