### ISSUE TITLE
Group video streaming problem

### ISSUE THREAD

**Issue by dimpleagola** [praween05/Android-SignalView#2]
Hey sorry  for answer this  repository.
I need your help. I thing you are using live stream in your project.

I am using Wowza  and AntMedia server for video streaming. The live stream is coming in form of RTSP URL. I want to stream it in android. Also I need to play multiple RTSP URL at the same time on same page ie group video conferencing. 

Peer to Peer connection is possible. and One to many is also working.

But I need many to many & many to one streaming. 
Please help ...

**Comment by praween05** [comment]
Hello dimpleagola 

Wowza itself provides his own video player. I have used that for many to many video conferencing. You can look into it. It have a video and audio streaming simultaneously from multiple user though there are some lag in audio and video but it is still pretty much OK. The lagging time is less than a second.

**Comment by praween05** [comment]
https://www.wowza.com/docs/getting-started-with-wowza-player

This is the reference link for Wowza video player.

**Comment by dimpleagola** [comment]
Thank you for your support. I will check the Wowza server.
